// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

// #include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// fastLR_
Rcpp::List fastLR_(double eps_f, double eps_g);
RcppExport SEXP _RcppNumerical_fastLR_(SEXP eps_fSEXP, SEXP eps_gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eps_f(eps_fSEXP);
    Rcpp::traits::input_parameter< double >::type eps_g(eps_gSEXP);
    rcpp_result_gen = Rcpp::wrap(fastLR_(eps_f, eps_g);
    return rcpp_result_gen;
END_RCPP
}
